Visualisations in bars and heatmap alls items interactions
e-ucm/t-mon pull request #13
Opened 2020-07-22 12:00 UTC by gorco

2020-07-22 12:01 UTC, gorco commented
#5 substitute

2020-07-22 14:19 UTC, jujusb approved these changes
After the correction of a file problem, it's all OK

2020-07-23 11:09 UTC, crisal24 requested changes
Good job! Some minor issues to fix.

2020-07-23 11:09 UTC, crisal24 commented on vis/xAPISG-ItemsActionTypeInteracted.ipynb
> +    "    #print(items)\n",
Delete commented lines

2020-07-23 11:09 UTC, crisal24 commented on vis/xAPISG-ItemsActionTypeInteracted.ipynb
> +    "            j=0\n",
Variable not updated/used

2020-07-23 11:09 UTC, crisal24 commented on vis/xAPISG-ItemsInteracted.ipynb
> +    "def find_list_item(players_info): \n",
In xAPISG-ItemsActionTypeInteracted similar functionality is performed directly in the main function, please unify (either create def also in the other notebook, or delete this here).

2020-07-23 11:09 UTC, crisal24 commented on vis/HelpersFunctions/HeatMap.ipynb
> +    "* typ : boolean if this action is divided in type or not\n",
Clarify / further document these variables for better understanding

2020-07-23 11:09 UTC, crisal24 commented on vis/HelpersFunctions/MultiBarSeparated.ipynb
> +    "* typ : boolean if this action is divided in type or not\n",
Clarify / further document these variables for better understanding

2020-07-23 11:09 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "%run vis/HelpersFunctions/MultiBarSeparated.ipynb\n",
Helper functions could better be run in the visualization notebook, to hide lower-level details here.

2020-07-23 11:09 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "%run vis/HelpersFunctions/HeatMap.ipynb\n",
Helper functions could better be run in the visualization notebook, to hide lower-level details here.

2020-07-23 11:09 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "%run vis/xAPISG-ItemsInteracted.ipynb\n",
Duplicated: already run in previous cell.

2020-07-23 11:09 UTC, crisal24 commented on xAPISGProcessor.ipynb
>   ],
Vis notebook xAPISG-ItemsActionTypeInteracted is not used.

2020-08-20 06:01 UTC, closed without merging