Add of toolbar with interactives save button, pans, home button, zoom…
e-ucm/t-mon pull request #20
Opened 2020-08-25 09:12 UTC by jujusb

… for the matplotlib plot

2020-08-26 11:29 UTC, crisal24 requested changes
Great work! After fixing a syntax error (see comment) and installing the new ipympl, the new toolbar was correctly displayed with great features to better visualize the data and save the plots. This could greatly improve the user experience!

Some issues found: 
- axis labels and titles seems not to be displayed now
- some top values in bar charts appear outside of the scope of the visualization

General comment about the code: as the code of the visualizations has increased with the new features, it could be helpful to add more comments in the code to help readers understand what is been done at each step. Consider revise the current code to improve documentation and comments as a next step (when funcionality is completed).

2020-08-26 11:29 UTC, crisal24 commented on vis/xAPISG-CompletablesScores.ipynb
> +    "            if len(completableSelected)>0 and len(playersSelected)>0::\n",
SyntaxError ::

2020-08-26 11:29 UTC, crisal24 commented on vis/xAPISG-CompletablesScores.ipynb
> +    "            n_groups = len(players_scores[n])\n",
n_groups never used

2020-08-26 11:29 UTC, crisal24 commented on vis/xAPISG-CompletablesProgress.ipynb
> +    "            n_groups = len(players_progress[n])\n",
n_groups never used

2020-08-26 11:29 UTC, crisal24 commented on vis/xAPISG-CompletablesTimes.ipynb
> -    "        if n_groups>0 :\n",
n_groups assignment (L79) now never used

2020-08-26 11:29 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "! jupyter nbextension enable ipympl --py --sys-prefix"
Is there another way to do this? Seems like too low level code to have it in the main notebook.

2020-08-31 09:12 UTC, crisal24 requested changes
Great work! Clear improvement in the visualizations & in the code with more comments to follow the process.

Ongoing issues: 
- No labels are displayed in the visualizations axis
- When updating the configuration in some visualizations (e.g. order), instead of updating the current visualization, the old is maintained, and the new appears below, which is a bit confusing.

2020-08-31 09:12 UTC, crisal24 commented on vis/xAPISG-AccessedAccessible.ipynb
> +    "**** vis_accessibles_function_time function** * display a bubble chart showing a bubble in function of the average of players has accessed this accessible in a certain period of time."
fix markdown **

2020-08-31 09:12 UTC, crisal24 commented on vis/xAPISG-AlternativesSelectedQuestion.ipynb
> +    "        #TODO only display the one selected in the accordion\n",
Missing TODO?

2020-08-31 09:12 UTC, crisal24 commented on vis/xAPISG-GamesStartedCompleted.ipynb
> +   "outputs": [
Clear NameError output

2020-08-31 09:12 UTC, crisal24 commented on vis/xAPISG-ItemsInteracted.ipynb
> +    "        #TODO only display the one selected in the accordion\n",
Missing TODO?

2020-08-31 09:12 UTC, crisal24 commented on vis/xAPISG-MenusSelected.ipynb
> +    "            #TODO only display the one selected in the accordion\n",
Missing TODO?

2020-09-03 10:35 UTC, crisal24 requested changes
Good work! Some minor changes.

2020-09-03 10:35 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "plt.style.use('dark_background')"
Could use the style "classic" as default? Or allow selection of style.

2020-09-03 10:35 UTC, crisal24 commented on vis/clearFigMatplotlib.ipynb
> +{
Could this file be in helpersFunction folder?

2020-09-03 10:35 UTC, crisal24 commented on vis/helpersFunctions/HeatMap.ipynb
> +    "\n",
Add inputs: figTab and figtitle

2020-09-03 10:35 UTC, crisal24 commented on vis/helpersFunctions/MultiBarSeparated.ipynb
> +    "\n",
add filetitle input

2020-09-03 10:35 UTC, crisal24 commented on vis/xAPISG-CompletablesScores.ipynb
> +    "%run vis/helpersFunctions/OrderGraphValuesAndSelectDataByXaxis.ipyn"
ipynb?

2020-09-04 09:13 UTC, crisal24 requested changes
Good additions! See minor changes in the comments.

Also, revise the size of the output view, which gets smaller when changing between tabs.

2020-09-04 09:13 UTC, crisal24 commented on xAPISGProcessor.ipynb
> +    "def on_selected_tab_index_change(change):\n",
Could this code be hidden in another notebook?

2020-09-04 09:13 UTC, crisal24 commented on globalsSelectors.ipynb
> +    "global style\n",
Great addition! Maybe the selection is a bit complex now, could the dropdown be limited to a selection of all the available styles? (e.g. up to 10 which are different enough between them)

2020-09-04 11:06 UTC, jujusb commented
> Good additions! See minor changes in the comments.
> 
> Also, revise the size of the output view, which gets smaller when changing between tabs.

The size of the output can be corrected but you need to install nodejs in your computer to execute the line that correct that.

2020-09-04 14:11 UTC, crisal24 approved these changes
Great work! Display of visualizations has clearly improved! Ready to merge

2020-09-04 14:12 UTC, merged