Correctionsvisualisations
e-ucm/t-mon pull request #4
Opened 2020-07-10 11:36 UTC by jujusb

2020-07-15 12:14 UTC, gorco requested changes
Review completed. Good job. 

I've left some comments in the code and other following to improve the code and visualizations:
I think we can improve some of the visualizations by adding options. In the case of the "CorrectIncorrectPlayer", "CorrectIncorrectQuestion" and "VideosSeenSkiped" displays we could add the option of a "normalized", i.e. being the Y-axis the percentage from 0 to 100. That can be useful to know which question has a higher error rate regardless of whether it appears more or less.

Anyway, we have several problems with the displays that we should solve before create more visualizations. Although there is no need to make changes in this PR, it is necessary to address it as soon as possible. 
- If there is no data to fill a visualization nothing is shown. In this case at least some message should be shown.
- There are cases in which if there is a lot of data, options or users, the display is unable to show them and also the bars are not adjusted. I think it is best to meet to discuss the issue and decide how to address this problem.

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-CompletablesProgress.ipynb
> +    "    scoremin=float('Inf')\n",
Please, can you change the var names? The visualization is about progress and not about score

```suggestion
    "    progressmin=float('Inf')\n",
```

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-CompletablesProgress.ipynb
> +    "        scoremin-=1\n",
This is the minimun progress of the user and it can never be _<0_. 
E.g: If "scoremin" is _0.1_ "scororemin" will be _-1.1_

Also, please, change the var. name, the visualization is about the user progress. This name confuses

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-CompletablesProgress.ipynb
>      "    opacity = 0.8\n",
This variable is never used

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-CompletablesProgress.ipynb
> +    "        plt.ylabel(\"Progress\")\n",
I think we should specify the range of values it can take, p.g. "Progress (0 to 1)" and also, I think that is better if we use % in all visualizations like this, i.e use 0% to 100%. If the value is 0.75 we have to transform to 75. 
What do you think @crisal24 ?

2020-07-15 12:14 UTC, gorco commented on ProcessxAPISGStatement.ipynb
> +    "            if object_type_xapi in [\"Alternative\",\"alternative\"]:\n",
I think is better use .lower()
`if object_type_xapi.lower() =="alternative"`
And same in other cases. The change allows to work with the word "alternative" regardless of how it is written (upper,  lower or capital case)

2020-07-15 12:14 UTC, gorco commented on ProcessxAPISGStatement.ipynb
> +    "                for timeformat in ('%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S.%fZ'):\n",
I understand that you want to check diferents time formats. I see the time format like a configurable variable (maybe an array of formats) that user can change easely like the traces file directory. And also we can transform this block of code in a function that return the value if any format match and show a warning/exception if not

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-CompletablesScores.ipynb
>      "    opacity = 0.8\n",
Not used

2020-07-15 12:14 UTC, gorco commented on vis/xAPISG-PlayersProgress.ipynb
> +    "            #print(progress_time)\n",
Remove the commented code, please

2020-07-16 06:29 UTC, jujusb commented on vis/xAPISG-CompletablesProgress.ipynb
> +    "    scoremin=float('Inf')\n",
Corrected in the last commit

2020-07-16 06:29 UTC, jujusb commented on vis/xAPISG-CompletablesProgress.ipynb
>      "    opacity = 0.8\n",
Corrected in the last commit

2020-07-16 06:29 UTC, jujusb commented on ProcessxAPISGStatement.ipynb
> +    "                for timeformat in ('%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S.%fZ'):\n",
Corrected in the last commit

2020-07-16 06:29 UTC, jujusb commented on vis/xAPISG-CompletablesScores.ipynb
>      "    opacity = 0.8\n",
Corrected in the last commit

2020-07-16 06:29 UTC, jujusb commented on vis/xAPISG-PlayersProgress.ipynb
> +    "            #print(progress_time)\n",
Corrected in the last commit

2020-07-17 15:28 UTC, closed without merging